#!/usr/bin/env python3
import sys
import os.path
import re



def print_error(message):
        print(message)
        sys.exit(1)


def newZone(name):

	zone = name + ".joran-trompet.sb.uclllabs.be"
	path = "/etc/bind/zones/" + zone

	with open(path, "w+") as file:
		file.write("$TTL 604800\n")
		file.write("@  IN  SOA " + zone + " root.joran-trompet.sb.uclllabs.be. (\n")
		file.write("  1 ;serial\n")
		file.write("  2h ;refresh\n")
		file.write("  1h ;retry\n")
		file.write("  1w ;expire\n")
		file.write("  5 ) ;neg cache TTL\n")
		file.write(";\n\n")
		file.write("\t".join(["@", "IN", "NS", "ns.joran-trompet.sb.uclllabs.be."]) + "\n")
		file.write("\t".join(["@", "IN", "NS", "ns1.uclllabs.be."]) + "\n")
		file.write("\t".join(["@", "IN", "NS", "ns2.uclllabs.be."]) + "\n")
		file.write(";\n\n")
		file.write("\t".join(["@", "IN", "A", "193.191.177.158"]) + "\n")
		file.write("\t".join(["ns", "IN", "A", "193.191.177.158"]) + "\n")

	with open("/etc/bind/zones/joran-trompet.sb.uclllabs.be", "a") as file:
		file.write("\t".join([name, "IN", "NS", "ns"]) + "\n")

	with open("/etc/bind/named.conf.local", "a") as file:
		file.write("\nzone \"" + name + ".joran-trompet.sb.uclllabs.be\" {\n")
		file.write("  type master;\n")
		file.write("  file \"" + path + "\";\n")
		file.write("   allow-transfer {193.191.177.254;193.191.177.254;193.191.177.4;193.191.177.221; };\n") 
		file.write("};\n")


if __name__ == '__main__':
	args = sys.argv
	args.pop(0)
	if len(args) == 1:
		name = args[0]
		if re.match("^[A-Za-z0-9]*$", name):
			newZone(name)
		else:
			print_error("error1")
	else:
		print_error("error2")
