#!/usr/bin/env python3
import sys
import os.path

#test
def print_error(message):
	print(message)
	sys.exit(1)

def get_type_from_args(args, delete = False):
	if('-t' in args):
		index = args.index('-t')
		type = args[index + 1]
		if delete:
			for _ in range(2):
				args.pop(index)
	else:
		type = "A"
	return type

def remove_first_del(string, delimiter):
	string_list = string.split(delimiter)
	string_list.pop(0)
	result = delimiter.join(string_list)
	return result

def add_to_zone(line, zone):

	zone_file_location = "/etc/bind/zones/" + zone
	exists = os.path.isfile(zone_file_location)
	if not exists:
		print_error(zone + " NOT exist: " + zone_file_location)

	with open(zone_file_location, "a") as file:
		print("SUCCES: " + line + " to zone " + zone)
		file.write(line)
		file.write("\n")


if __name__ == '__main__':
	args = sys.argv
	args.pop(0)
	type = get_type_from_args(args, True)

	if type == 'CNAME':
		if len(args) != 2:
			print(args)
			print_error("ERROR1")
		name = args[0]
		address = args[1]
		zone = remove_first_del(address, '.')
		add_to_zone('\t'.join([name, 'IN', type, address]), zone)
	elif type == 'A':
		if len(args) != 3:
			print(args)
			print_error("ERROR2")
		alias_name = args[0]
		ip = args[1]
		zone = args[2]
		add_to_zone('\t'.join([alias_name, 'IN', type, ip]), zone)
	elif type == 'MX':
		if len(args) != 3:
			print(args)
			print_error("ERROR3")
		name = args[0]
		ip = args[1]
		zone = args[2]
		add_to_zone('\t'.join([zone, 'IN', type,'10', name]), zone)
		add_to_zone('\t'.join([name, 'IN', 'A', ip]), zone)

